const vm = require('node:vm');
const fs = require('node:fs');
const assert = require('node:assert/strict');
let expenses = [];
const context = { window: { store: { getExpenses: () => expenses } } };
vm.createContext(context);
for (const file of ['js/expense-split.js', 'js/settlement.js']) vm.runInContext(fs.readFileSync(file, 'utf8'), context);
const split = context.window.expenseSplit;
const rows = values => values.map((value, index) => ({ name: ['Ana', 'Beto', 'Caro'][index], selected: true, value }));
const amounts = split.build(30000, 'amount', rows([15000, 10000, 5000]));
expenses = [{ amount: 30000, paidBy: 'Ana', split: amounts }];
let result = context.window.settlementManager.calculate('2026-09');
assert.equal(result.transfers.length, 2);
assert.equal(result.balances.find(p => p.name === 'Ana').net, 15000);
assert.equal(result.balances.find(p => p.name === 'Beto').net, -10000);
assert.equal(result.balances.find(p => p.name === 'Caro').net, -5000);
const equal = split.build(100, 'equal', rows([0,0,0]));
assert.equal(equal.participants.reduce((n,p) => n + p.cents, 0), 10000);
assert.equal(equal.participants[0].cents, 3334);
const percent = split.build(0.05, 'percent', rows([50, 25, 25]));
assert.equal(percent.participants.reduce((n,p) => n + p.cents, 0), 5);
assert.throws(() => split.build(10, 'percent', rows([50,20,20])), /100%/);
assert.throws(() => split.build(10, 'amount', rows([1,2,3])), /exactamente/);
assert.throws(() => split.build(10, 'equal', []), /persona/);
assert.throws(() => split.build(10, 'amount', rows([-1,5,6])), /positivos/);
expenses.push({ amount: 900, paidBy: 'Otro' });
result = context.window.settlementManager.calculate('2026-09');
assert.equal(result.unassigned, 1);
assert.equal(result.totalSpent, 30000);
expenses = [{ amount: 0.05, paidBy: 'Ana', split: percent }];
result = context.window.settlementManager.calculate('2026-09');
assert.equal(result.transfers.reduce((n,t) => n + Math.round(t.amount * 100), 0), 2);
// Serialización de nube/respaldo conserva exactamente el reparto.
assert.equal(JSON.stringify(JSON.parse(JSON.stringify(amounts))), JSON.stringify(amounts));
console.log('OK: montos, porcentajes, iguales, centavos, validación y gastos anteriores.');
